pruning

diff --git a/teddy/Makefile b/teddy/Makefile
--- a/teddy/Makefile
+++ b/teddy/Makefile
@@ -54,19 +54,34 @@ update_sources:
 			for sub in $$subs; do \
 				wget -nc https://hls.ted.com/project_masters/$$file/$$sub -O vtt/$$file/`basename $$sub` 2>/dev/null;\
 			done;\
+			if [ -e `grep -l "Sorry, we could not find subtitles" vtt/$$file/* | head -n 1` ]; then \
+				rm `grep -l "Sorry, we could not find subtitles" vtt/$$file/*`; \
+			fi;\
 			if rmdir vtt/$$file 2>/dev/null; then echo ' empty' 1>&2; else echo ' '; ls vtt/$$file | perl -pe 's/\s/ /g; s/\.vtt//g;' 1>&2; echo 1>&2; fi;\
 		fi;\
 	done;
+	for dir in vtt/*; do \
+		
+
+			done
 	make update_segments
 
 # automatically called after make update_sources
 update_segments: vtt
+	for dir in vtt/*/; do \
+		if [ -e `grep -l "Sorry, we could not find subtitles" $$dir/* | head -n 1` ]; then \
+			echo `grep -l "Sorry, we could not find subtitles" $$dir/* | head -n 1`; \
+			rm `grep -l "Sorry, we could not find subtitles" $$dir/*`; \
+			echo -n $$dir' ' 1>&2; \
+			if rmdir vtt/$$file 2>/dev/null; then echo ' empty' 1>&2; else echo ' '; ls vtt/$$file | perl -pe 's/\s/ /g; s/\.vtt//g;' 1>&2; echo 1>&2; fi;\
+		fi;\
+	done;\
 	for sub in vtt/*/*vtt; do \
 		if [ ! -e $$sub.1 ]; then \
 			nr=`echo $$sub | cut -f 2 -d '/'`;\
 			for seg in {1..9999}; do \
 				wget -nc https://hls.ted.com/project_masters/$$nr/subtitles/`basename $$sub`'?segment='$$seg -O $$sub.$$seg 2>/dev/null;\
-				if cat $$sub.$$seg | grep -v '^00:00:00.000' | grep -m 1 '\-\->' >/dev/null; then \
+				if cat $$sub.$$seg | grep -v '^00:00:00.000' | grep -v 'Sorry, we could not find subtitles' | grep -m 1 '\-\->' >/dev/null; then \
 					echo $$sub.$$seg;\
 				else \
 					rm $$sub.$$seg;\
